# Generated by Django 3.2.9 on 2021-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tema', models.PositiveIntegerField(help_text='Uno de los grandes temas del curso.')),
            ],
        ),
    ]
