# Generated by Django 3.1.1 on 2020-12-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccionunica',
            name='vol',
            field=models.IntegerField(null=True),
        ),
    ]
