# Generated by Django 3.1.6 on 2021-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
