# Generated by Django 3.1.6 on 2021-02-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='tema',
            field=models.PositiveIntegerField(default=1, help_text='Uno de los grandes temas del curso.'),
            preserve_default=False,
        ),
    ]
